### ISSUE TITLE
Compilation fails with current Artful toolchain

### ISSUE THREAD

**Issue by evsh** [suaefar/ryzen-test#17]
When using daily Artful image, the test compilation fails due to a regular compilation error. Excuse me, I can't give the error message since I was using a live USB session. Maybe updating target GCC version (to 7.2) would help?

**Comment by evsh** [comment]
The error is the same as in #6.

**Comment by Oxalin** [comment]
Could you be more specific please? Also see comment newly added under #6

**Comment by Oxalin** [comment]
Hi again. I've created a branch with some fixes that should take care of your problem. It would be useful if you could test it and comment the discussion with your results. Please, see pull request #18

**Comment by suaefar** [comment]
I merged the pull request.
@evsh, could you try to pull the latest changes (or just download/clone the repository again) and see if the script now runs fine?

**Comment by tobbez** [comment]
Can confirm that it works on Ubuntu 17.10 (artful).

**Comment by suaefar** [comment]
@tobbez Do you have a faulty CPU to test if it triggers the bug?
Does it segfault as expected in a few minutes?

**Comment by tobbez** [comment]
When called with `4 4` it generally failed within an hour or so.

**Comment by suaefar** [comment]
Thank you for your answer!
I think an hour is rather long and am not sure if we regressed performance wise (time to trigger the bug).

**Comment by tobbez** [comment]
We can't really reach a conclusion either way with this limited data.

Probability of failure (and thus, by extension time to failure) may vary between CPUs.

There are also a large number of other factors that may or may not affect the outcome (e.g. kernel version or hardware like motherboard and memory).

**Comment by suaefar** [comment]
Yes, that is true.
However, I saw 4 different faulty CPUs (1x1700 2x1700X 1x1800X) with different motherboards and all failed within a few minutes (on Ubuntu 17.04 compiling GCC 7.1 in parallel).
We need more data from users to decide.

**Comment by suaefar** [comment]
Artful is not supported!
See [README.md](https://github.com/suaefar/ryzen-test/blob/master/README.md#updaterevert-the-codebase-is-frozen)
